version: '3'
services:
  app:
    image: natagw1/laravel_action:${IMAGE_VER}
    container_name: laratm
    restart: unless-stopped
    tty: true
    volumes:
      - .env:/var/www/.env
    networks:
      - laratm-net

  nginx:
    image: natagw1/laravel_nginx_action:${IMAGE_VER}
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8002:80"
    depends_on:
      - app
    networks:
      - laratm-net

#Docker Networks
networks:
  laratm-net:
    driver: bridge